### PR TITLE
feat: add matomo tracking, cookie consent PSA-32

### PR DESCRIPTION
**Pull request by mikkojamG**
Add Matomo tracking.

Azure pipeline changes: https://dev.azure.com/City-of-Helsinki/pysakoinnin-sahk-asiointi/_git/pysakoinnin-sahk-asiointi-pipelines/pullrequest/10007

### CODE REVIEW

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://pysakoinnin-sahk-asiointi-pr170-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by danipran — APPROVED** [review]

**Pull request merged**
