### PR TITLE
PSA-11 api error catch

### PR DESCRIPTION
**Pull request by mikkojamG**
Uncatched errors are causing pollution in Sentry logs.

### CODE REVIEW

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr157-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr157-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**PYSAKOINNIN-SAHK-ASIOINTI-UI branch is deployed to platta: https://pysakoinnin-sahk-asiointi-pr157-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by arpargo — APPROVED** [review]
LGTM

**Pull request merged**
